version: 0.2


phases:

  build:
    commands:
      - echo Build started on `date`
      - mvn clean compile
  post_build:
    commands:
      - echo Build completed successfully

artifacts:
  files:
   - target/policyapp.jar

  discard-paths: yes



